### ISSUE TITLE
Missing and repeating keys

### ISSUE THREAD

**Issue by quozl** [sugarlabs/countries-activity#1]
Moved from https://github.com/sugarlabs/sugar/issues/755 after a report by @JarodO.

 * some keystrokes are missed,
 * some keystrokes may cause continual repeat as if a key is stuck,
 * more likely to happen if the press and release key events are close together,
 * log activity shows no useful errors,
 * other activities are not affected.

**Comment by nswarup14** [comment]
@quozl 

> some keystrokes are missed

I believe this was fixed by @pro-panda here #6 

> some keystrokes may cause continual repeat as if a key is stuck,

Even after much testing, I'm unable to reproduce the error. Could you guide me as to how to reproduce it. I believe this is the error I'm referring as in the screenshot.

![](https://cloud.githubusercontent.com/assets/8785617/26759230/5a516128-48ad-11e7-83c2-c3d67b50a831.jpg)

Thanks.

**Comment by quozl** [comment]
I'll try reproducing.

**Comment by quozl** [comment]
I've tested with Ubuntu 18.04 on physical hardware, not virtualised.  None of the problems reproduce.
