### ISSUE TITLE
Three Letters from double-click

### ISSUE THREAD

**Issue by ghost** [sugarlabs/countries-activity#2]
Issue:
When using a cursor to select the letters, if a letter is double-clicked (such as when typing the 'L's in "Holland") it will print three letters instead of two.

Suggestions:
If there is an action associated with double-clicking that prints two letters, it could be that the first click prints the letter and the second click activates the double-click action.

**Comment by quozl** [comment]
Thanks.  I've reproduced.

Event sequence I see is `{down,up,down,down,up}`, even though the underlying events were `{down,up,down,up}`.

PyGame on your system is probably 1.9.1.  PyGame is a wrapper for SDL.  SDL added a field to the mouse button down event for number of clicks, and began to detect double click events, you can see that mentioned in the 2.0.2 release notes.  https://github.com/SDL-mirror/SDL/blob/master/WhatsNew.txt#L363

But PyGame is not, as of 1.9.1, handling the clicks value, and is not passing it on to the application.

The second `down` event will have a `clicks=2`, but PyGame doesn't notice.

Countries activity would be best fixed by behaving like GTK, arming the buttons with MOUSEBUTTONDOWN, and activating the buttons with MOUSEBUTTONUP.

**Comment by nswarup14** [comment]
@quozl Thanks
You're right. PyGame version used while running the activity is 1.9.1. I think 1.9.1 is the default version of PyGame that comes when installing Sugar. (I was able to install 1.9.6 version of PyGame for python3 and for python2 I'm using 1.9.1)

> Countries activity would be best fixed by behaving like GTK, arming the buttons with MOUSEBUTTONDOWN, and activating the buttons with MOUSEBUTTONUP.

I did not quite understand the fix that you've proposed, and why you have mentioned GTK. Some clarification would help me understand the fix better.

Thanks

**Comment by pro-panda** [comment]
Gtk also allows you to detect keystrokes. See https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.signals.key_press_event

**Comment by quozl** [comment]
Thanks.  I'm certainly not suggesting using GTK.

GTK source code and _behaviour_ demonstrates the logic required by user interface push button widgets, in turn this arose from OSF/Motif and X11 decades ago.  Here's an english pseudo-code or paraphrase;

* enable mouse button down and up events,
* when mouse button down event occurs, and coordinate is within button, then set arm state, redraw button in arm state, and enable leave notify events,
* when leave notify event occurs, and button is armed, then disarm button, and redraw button in disarm state,
* when mouse button up event occurs, and coordinate is within button, and button is armed, then disarm button, redraw button in disarm state, disable leave notify events, and set activated state,

PyGame doesn't have buttons, and so doesn't have the equivalent of a leave notify event for a button.  That has to be synthesised with motion notify events, which are of type `pygame.MOTIONNOTIFY`.

Test cases for buttons;

* move pointer inside button, press mouse button, release; the button shall activate,
* move pointer outside button, press mouse button, move pointer inside button, release; the button shall not trigger,
* move pointer inside button, press mouse button, move pointer outside button, release; the button shall not trigger, _currently fails_ for this activity and many others by same author.

Also affected are touchpad tap to click, and touchscreen touch events.

Hope that helps.
